version: "3.7"
services:
  backend: &backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    image: backend-pldet
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    depends_on:
      - postgresql
    command: /start
  postgresql:
    image: postgres:13.4
    env_file:
      - .env
    ports:
      - 15432:5432
  rabbitmq:
    image: 'rabbitmq:3.8.14-alpine'
    ports:
      - 5672:5672
  celeryworker:
    <<: *backend
    image: celery-worker
    ports: [ ]
    depends_on:
      - postgresql
      - rabbitmq
    command: "celery -A app.celery worker -l DEBUG"
  flower:
    image: mher/flower
    command: [ "flower", "--broker=amqp://guest:guest@localhost:5672//", "--port=8888" ]
    ports:
      - 8888:8888