version: "3.7"
services:
  backend: &backend
    build:
      context: .
      dockerfile: docker/local/backend/Dockerfile
    ports:
      - 8000:8000
    image: backend-pldet
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    depends_on:
      - postgresql
    command: /start
  postgresql:
    image: postgres:13.4
    env_file:
      - .env
    ports:
      - 15432:5432
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
  rabbitmq:
    image: 'rabbitmq:3.8.14-alpine'
    ports:
      - 5672:5672
  celeryworker:
    <<: *backend
    image: celery-worker
    ports: [ ]
    depends_on:
      - postgresql
      - rabbitmq
    command: "celery -A app.celery worker -l DEBUG"
  celery-beat:
    <<: *backend
    image: celery-beat
    depends_on:
      - postgresql
      - rabbitmq
    command: "celery -A app.celery beat -l DEBUG"
    ports: [ ]
  flower:
    <<: *backend
    command: "celery -A app.celery flower  --broker=amqp://guest:guest@localhost:5672// "
    ports:
      - 5555:5555
    depends_on:
      - postgresql
      - rabbitmq
volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }