version: "3.7"
services:
  backend: &backend
    build:
      context: .
    ports:
      - 8000:8000
    image: backend-pldet
    volumes:
      - ./backend:/backend
  db:
      image: postgres:13.4
      env_file:
        - .env
      ports:
        - 15432:5432