[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = 'venv'
force-exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
| ./*/migrations
'''